language: r
sudo: false
cache: packages
latex: false

before_install:
    - pip install urllib3 ga4gh --user

r_github_packages:
  - jimhester/lintr

warnings_are_errors: false

notifications:
    email:
    on_success: change
    on_failure: always

after_success:
    - Rscript -e 'covr::codecov()'
    - Rscript -e 'lintr::lint_package()'
